@hostname = localhost
@port = 3333
@contentType = application/json
@createdAt = {{$datetime iso8601}}
@modifiedBy = {{$processEnv USERNAME}}
@baseURL = http://{{hostname}}:{{port}}
@authToken = Bearer {{loginAPI.response.body.token}}
@userId = {{loginAPI.response.body.user.id}}

###
# @name createUser

POST {{baseURL}}/users
Content-Type: {{contentType}}

{
  "name": "Yuri Almeida",
  "email": "yurialves2@gmail.com",
  "password": "çenha"
}

###

# @name createUser2

POST {{baseURL}}/users
Content-Type: {{contentType}}

{
  "name": "John Doe",
  "email": "johndoe@gmail.com",
  "password": "password"
}

### Sessions
# @name loginAPI

POST {{baseURL}}/sessions
Content-Type: {{contentType}}

{
  "email": "yurialves2@gmail.com",
  "password": "çenha"
}

###
# @name loginAPI

POST {{baseURL}}/sessions
Content-Type: {{contentType}}

{
  "email": "johndoe@gmail.com",
  "password": "password"
}

###
# @name uploadUserAvatar
PATCH {{baseURL}}/users/avatar
Authorization: {{authToken}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="key"

value
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="key"

value
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="avatar-example.drawio.png"
Content-Type: image/png

< ./avatar-example.drawio.png

------WebKitFormBoundary7MA4YWxkTrZu0gW--


###
# @name createAppointments

POST {{baseURL}}/appointments
Content-Type: {{contentType}}
Authorization: {{authToken}}

{
  "provider_id": "0488640e-860b-46ef-a952-3a866a44c914",
  "_provider_id": "{{userId}}",
  "date": "2020-10-07T13:00:00",
  "_date": "{{createdAt}}"
}

###
# @name listAppointments

GET {{baseURL}}/appointments/me
  ?day=6
  &month=10
  &year=2020
Authorization: {{authToken}}

###

# @name forgotPassword

POST {{baseURL}}/password/forgot
Content-Type: application/json

{
  "email": "yurialves2@gmail.com"
}

###

# @name resetPassword

POST {{baseURL}}/password/reset
Content-Type: application/json

{
  "token": "c69760ca-b485-459a-b928-58680e3dbfeb",
  "password": "123123"
}

###

# @name showProfile

GET {{baseURL}}/profile
Content-Type: application/json
Authorization: {{authToken}}


###

# @name updateProfile

PUT {{baseURL}}/profile
Content-Type: application/json
Authorization: {{authToken}}

{
  "name": "Yuri Alves",
  "email": "yurialves2@gmail.com"
}

###

# @name listProviders

GET {{baseURL}}/providers
Authorization: {{authToken}}

###
