@hostname = localhost
@port = 3333
@contentType = application/json
@createdAt = {{$datetime iso8601}}
@modifiedBy = {{$processEnv USERNAME}}
@baseURL = http://{{hostname}}:{{port}}
@authToken = Bearer {{loginAPI.response.body.token}}
@userId = {{loginAPI.response.body.user.id}}

###
# @name createUser

POST {{baseURL}}/users
Content-Type: {{contentType}}

{
  "name": "Yuri Alves",
  "email": "yurialves2@gmail.com",
  "password": "çenha"
}

### Sessions
# @name loginAPI

POST {{baseURL}}/sessions
Content-Type: {{contentType}}

{
  "email": "yurialves2@gmail.com",
  "password": "çenha"
}


###
# @name uploadUserAvatar
PATCH {{baseURL}}/users/avatar
Authorization: {{authToken}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="key"

value
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="key"

value
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="avatar-example.drawio.png"
Content-Type: image/png

< ./avatar-example.drawio.png

------WebKitFormBoundary7MA4YWxkTrZu0gW--


###
# @name createAppointments

POST {{baseURL}}/appointments
Content-Type: {{contentType}}
Authorization: {{authToken}}

{
  "provider_id": "{{userId}}",
  "date": "{{createdAt}}"
}

###
# @name listAppointments

GET {{baseURL}}/appointments
Authorization: {{authToken}}

###

# @name forgotPassword

POST {{baseURL}}/password/forgot
Content-Type: application/json

{
  "email": "yurialves2@gmail.com"
}

###

# @name resetPassword

POST {{baseURL}}/password/reset
Content-Type: application/json

{
  "token": "c69760ca-b485-459a-b928-58680e3dbfeb",
  "password": "123123"
}
